# Site settings ...
uri: domain.com
url: https://domain.com
name: lilintech
title: Lilintech
email: lilintech@outlook.com
author: lilintech
keywords: "Your, Keyword, Here"
description: "My portfolio and blog site."
social_username: lilintech

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji